Repository shagun25/SheHeroes, pull requests merged in 2021-04, with the labels that each got.

#74 Added pedantic file
  Sheheroes_WatchOS/pubspec.yaml
  analysis_options.yaml
  lib/main.dart
  lib/pages/AR.dart
  lib/pages/Voice.dart
  lib/pages/camera.dart
  lib/pages/cameraswitcher.dart
  lib/pages/center_map.dart
  lib/pages/emergency_dashboard.dart
  lib/pages/emergency_map.dart
  lib/pages/emergency_people_list.dart
  lib/pages/fake_call_support.dart
  lib/pages/fake_incoming_call_screen.dart
  lib/pages/login_page.dart
  lib/pages/main_dashboard.dart
  lib/pages/materialButton.dart
  lib/pages/nearby_places.dart
  lib/pages/notes.dart
  lib/pages/photo_capture.dart
  lib/pages/preview_screen.dart
  lib/pages/self_defence.dart
  lib/pages/sos.dart
  lib/pages/switcher.dart
  lib/pages/video_capture.dart
  lib/providers/emergency_details.dart
  lib/providers/profile_provider.dart
  lib/services/calls_and_messages_service.dart
  lib/services/googleAuth.dart
  lib/services/shake.dart
  lib/shared/bubble_indication_painter.dart
  lib/shared/constants.dart
  lib/shared/theme.dart
  lib/shared/widgets/bottom_bar.dart
  lib/shared/widgets/circular_button.dart
  lib/shared/widgets/drawer.dart
  lib/shared/widgets/gradient.dart
  lib/shared/widgets/profile_card.dart
  lib/shared/widgets/round_app_bar.dart
  lib/shared/widgets/sos_button.dart
  lib/ui/homescreen.dart
  lib/ui/splash.dart
Labels: Level3, gssoc21

#73 Background Image Capture added as Immediate Capture with quick Actions
  lib/main.dart
  lib/services/calls_and_messages_service.dart
Labels: Level3, gssoc21

#76 Fixed the overflowed signup screen
  lib/pages/login_page.dart
Labels: Level2, gssoc21

#70 Gitignore
  .gitignore
Labels: Level2, gssoc21

#82 Now If the user already logged in, then directly he/she navigate to the `switcher` page instead of `login` page
  lib/pages/login_page.dart
  lib/ui/splash.dart
Labels: Level2, gssoc21

#83 Readme file enhanced
  README.md
Labels: Level0, gssoc21

#84 Record Video In Background Added with Quick Actions
  lib/main.dart
  lib/services/calls_and_messages_service.dart
Labels: Level2, gssoc21

#91 Added the #187 with required changes
  README.md
Labels: Level0, gssoc21
