Repository shagun25/SheHeroes, pull requests merged in 2021-03, with the labels that each got.

#15 Added code of conduct
  CODE_OF_CONDUCT.md
  README.md
Labels: Level2, gssoc21

#44 Quickfix: Broken CODE_OF_CONDUCT.md link
  README.md
Labels: Level0, bug, easy, enhancement, gssoc21

#42 Welcome-bot
  .github/config.yml
Labels: Level2, gssoc21

#57 Google Authentication Added with Log-in and Log-Out Facility
  android/app/google-services.json
  android/app/src/main/kotlin/shagungoyal/safety/MainActivity.kt
  android/app/src/main/res/drawable-v21/launch_background.xml
  android/app/src/main/res/values-night/styles.xml
  assets/google.png
  lib/main.dart
  lib/pages/emergency_dashboard.dart
  lib/pages/login_page.dart
  lib/services/googleAuth.dart
  lib/ui/homescreen.dart
  lib/utils/routes.dart
  pubspec.lock
  pubspec.yaml
Labels: Level2, gssoc21

#63 #issue30 SOS without opening app in emergency - added shortcut from homescreen
  Sheheroes_WatchOS/lib/main.dart
  Sheheroes_WatchOS/pubspec.lock
  android/app/build.gradle
  android/settings_aar.gradle
  lib/main.dart
  lib/services/googleAuth.dart
  pubspec.yaml
Labels: Level3, gssoc21

#64 Added meta viewport to control the layout of website on the mobile br…
  Sheheroes_WatchOS/web/index.html
Labels: Level3, gssoc21

#62 Added Video Capture functionality (In Foreground)
  android/app/build.gradle
  android/gradle/settings_aar.gradle
  lib/pages/video_capture.dart
  lib/ui/homescreen.dart
  lib/utils/routes.dart
Labels: Level3, gssoc21

#69 Fake Call Functionality Added Integrate With Emergency Dashboard
  android/app/src/main/AndroidManifest.xml
  assets/fakeCallBG.jpg
  assets/mapImage.jpg
  lib/pages/emergency_dashboard.dart
  lib/pages/fake_call_support.dart
  lib/pages/fake_incoming_call_screen.dart
  lib/pages/switcher.dart
  lib/pages/video_capture.dart
  lib/ui/homescreen.dart
  lib/utils/routes.dart
  pubspec.yaml
Labels: Level3, gssoc21
